name = "Lean Maze game"
version = "3.0.0"
extra_files = "extras"
intro = "src/game/intro.lean"

[[worlds]]
name = "Four mazes"
id = 1
levels = [
	"src/mazes/example_maze/level.lean",
	"src/mazes/maze_with_fire/level.lean",
	"src/mazes/noneuclidean_maze/level.lean",
	"src/mazes/gcd_maze/level813.lean",
        "src/mazes/gcd_maze/level_challenge.lean",

]
